services:
  streamlit_app:
    build: .
    container_name: streamlit_container
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
